export function formatFecha(isoDate) {
  const meses = ['ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic']
  const fecha = new Date(isoDate)

  const dia = fecha.getDate()
  const mes = meses[fecha.getMonth()]
  const anio = fecha.getFullYear()

  let horas = fecha.getHours()
  const minutos = fecha.getMinutes().toString().padStart(2, '0')
  const periodo = horas >= 12 ? 'pm' : 'am'

  horas = horas % 12 || 12 // Ajusta el formato de 24h a 12h

  return `${dia} ${mes} ${anio} ${horas}:${minutos}${periodo}`
}

export const MunicipiosPR = [
  'Adjuntas',
  'Aguada',
  'Aguadilla',
  'Aguas Buenas',
  'Aibonito',
  'Arecibo',
  'Arroyo',
  'Añasco',
  'Barceloneta',
  'Barranquitas',
  'Bayamón',
  'Cabo Rojo',
  'Caguas',
  'Camuy',
  'Canóvanas',
  'Carolina',
  'Cataño',
  'Cayey',
  'Ceiba',
  'Ciales',
  'Cidra',
  'Coamo',
  'Comerío',
  'Corozal',
  'Culebra',
  'Dorado',
  'Fajardo',
  'Florida',
  'Florida, USA',
  'Guayama',
  'Guayanilla',
  'Guaynabo',
  'Gurabo',
  'Guánica',
  'Hatillo',
  'Hormigueros',
  'Humacao',
  'Isabela',
  'Jayuya',
  'Juana Díaz',
  'Juncos',
  'Lajas',
  'Lares',
  'Las Marías',
  'Las Piedras',
  'Loiza',
  'Luquillo',
  'Manatí',
  'Maricao',
  'Maunabo',
  'Mayagüez',
  'Moca',
  'Morovis',
  'Naguabo',
  'Naranjito',
  'Orocovis',
  'Patillas',
  'Peñuelas',
  'Ponce',
  'Quebradillas',
  'Rincón',
  'Rio Grande',
  'Sabana Grande',
  'Salinas',
  'San Germán',
  'San Juan',
  'San Lorenzo',
  'San Sebastián',
  'Santa Isabel',
  'Toa Alta',
  'Toa Baja',
  'Trujillo Alto',
  'Utuado',
  'Vega Alta',
  'Vega Baja',
  'Vieques',
  'Villalba',
  'Yabucoa',
  'Yauco',
]
export const productsFL = [
  'Enphase PV',
  'Enphase Encharge Battery',
  'Generac PV',
  'Tesla Batteries',
  'Generac Batteries',
  'Generac Generator',
  'Propane Gas Tank',
  'Generac Essential',
  'Generac Extended Power',
  'Generac Power Plus',
  'Roofing',
  'Other',
]
export const productsPR = ['Placas', 'Tesla Powerwall', 'Anker', 'Roofing']
export const appointmentOptionFL = ['Telefono', 'Virtual', 'Showroom - Roosevelt', 'Showroom - Ponce', 'Showroom - Hatillo', 'Showroom - Mayaguez']
export const appointmentOptionPR = ['Showroom - Roosevelt', 'Showroom - Ponce', 'Showroom - Hatillo', 'Showroom - Mayaguez']
export const destinationLearnAndWind = ['Las Vegas', 'Atlanta', 'Cancun', 'Punta Cana', 'Nashville']
export const CityFL = [
  'Alachua',
  'Aberdeen',
  'Alden Pines',
  'Alexander Springs',
  'Alford',
  'Allandale',
  'Allentown',
  'Alligator Point',
  'Altamonte Springs',
  'Altha',
  'Alton',
  'Altoona',
  'Alturas',
  'Alva',
  'Amelia City',
  'Anclote',
  'Andrews',
  'Andytown',
  'Anna Maria',
  'Anthony',
  'Apalachicola',
  'Apollo Beach',
  'Apopka',
  'Arborwood',
  'Arcadia',
  'Archer',
  'Argyle',
  'Aripeka',
  'Ashville',
  'Astatula',
  'Astor',
  'Athena',
  'Atlantic Beach',
  'Atlantis',
  'Atmore',
  'Attapulgus',
  'Auburndale',
  'Avalon Beach',
  'Ave Maria',
  'Aventura',
  'Avon Park',
  'Babson Park',
  'Bagdad',
  'Bahía de la Palma',
  'Bainbridge',
  'Baird',
  'Baker',
  'Bal Harbour',
  'Baldwin',
  'Barberville',
  'Bartow',
  'Bascom',
  'Basinger',
  'Bay Harbor Islands',
  'Bay Minette',
  'Bay Point',
  'Bayport',
  'Beacon Square',
  'Bell',
  'Belle Glade',
  'Belleair',
  'Belleair Beach',
  'Belleair Bluffs',
  'Belleair Shore',
  'Belleview',
  'Bellview',
  'Berrydale',
  'Bethune Beach',
  'Beulah',
  'Beverly Beach',
  'Beverly Hills',
  'Big Coppitt Key',
  'Big Pine Key',
  'Bimini',
  'Bithlo',
  'Black Diamond',
  'Black Jack Island',
  'Blocker',
  'Blountstown',
  'Boca Del Mar',
  'Boca Grande',
  'Boca Pointe',
  'Boca Raton',
  'Bokeelia',
  'Bonifay',
  'Bonita Springs',
  'Bostwick',
  'Boulogne',
  'Bowling Green',
  'Boynton Beach',
  'Bradenton',
  'Bradenton Beach',
  'Bradfordville',
  'Brandon',
  'Branford',
  'Brent',
  'Brewton',
  'Briny Breezes',
  'Bristol',
  'Bronson',
  'Brooker',
  'Brookridge',
  'Brooksville',
  'Bruce',
  'Bryceville',
  'Buckhead Ridge',
  'Buckingham',
  'Bunnell',
  'Burnt Store Marina',
  'Bushnell',
  'Cabo Cañaveral',
  'Callahan',
  'Callaway',
  'Calle principal de Fort Pierce',
  'Campbellton',
  'Canal Point',
  'Cantonment',
  'Cape Coral',
  'Cape San Blas',
  'Capps',
  'Captiva',
  'Carrabelle',
  'Caryville',
  'Cassadaga',
  'Casselberry',
  'Caxambas',
  'Cedar Grove',
  'Cedar Key',
  'Celebration',
  'Center Hill',
  'Century',
  'Chassahowitzka',
  'Chattahoochee',
  'Chiefland',
  'Chipley',
  'Choctaw Beach',
  'Chokoloskee',
  'Christmas',
  'Chuluota',
  'Cinco Bayou',
  'Citra',
  'Citrus Hills',
  'Citrus Springs',
  'Ciudad de Panamá',
  'Clearwater',
  'Clearwater Beach',
  'Clermont',
  'Cleveland',
  'Clewiston',
  'Cloud Lake',
  'Cocoa',
  'Cocoa Beach',
  'Cocoa West',
  'Coconut Creek',
  'Cody',
  'Coleman',
  'Conch Key',
  'Cooper City',
  'Coopertown',
  'Copeland',
  'Coral Gables',
  'Coral Springs',
  'Cortez',
  'Cottondale',
  'Cow Key',
  'Crawford',
  'Crawfordville',
  'Creighton',
  'Crescent City',
  'Crestview',
  'Crooked Lake',
  'Crooked Lake Park',
  'Cross City',
  'Cross Creek',
  'Crystal Beach',
  'Crystal Lake',
  'Crystal River',
  'Crystal Springs',
  'Cutler Bay',
  'Cypress',
  'Cypress Gardens',
  'Cypress Lake',
  'Cypress Lakes',
  'Dade City',
  'Dania Beach',
  'Danks Corner',
  'Davenport',
  'Davie',
  'Day',
  'Daytona Beach',
  'Daytona Beach Shores',
  'De Funiak Springs',
  'DeBary',
  'DeLand',
  'DeLeon Springs',
  'Deer Park',
  'Deerfield Beach',
  'Delray Beach',
  'Deltona',
  'Destin',
  'Distrito histórico de Arcadia',
  'Dona Vista',
  'Donalsonville',
  'Doral',
  'Dover',
  'Dowling Park',
  'Drifton',
  'Duette',
  'Dundee',
  'Dunedin',
  'Dunnellon',
  'Dupont',
  'Eagle Lake',
  'Earleton',
  'East Lake',
  'East Palatka',
  'East Tampa',
  'Eastlake Weir',
  'Eastpoint',
  'Eaton Park',
  'Eatonville',
  'Ebro',
  'Eden',
  'Edgeville',
  'Edgewater',
  'El Jobean',
  'Elberta',
  'Elfers',
  'Elkton',
  'Ellenton',
  'Eloise',
  'Englewood',
  'Ensley',
  'Estero',
  'Esto',
  'Eustis',
  'Everglades City',
  'Evinston',
  'Fairfield',
  'Fanning Springs',
  'Fargo',
  'Felda',
  'Fellsmere',
  'Fern Park',
  'Fernandina Beach',
  'Ferndale',
  'Ferry Pass',
  'Fish Creek',
  'Flagler Beach',
  'Flamingo',
  'Flamingo Bay',
  'Flomaton',
  'Florahome',
  'Floral City',
  'Florala',
  'Florida City',
  'Florida Ridge',
  'Folkston',
  'Forest City',
  'Fort Green',
  'Fort Lauderdale',
  'Fort McCoy',
  'Fort Meade',
  'Fort Myers',
  'Fort Myers Beach',
  'Fort Ogden',
  'Fort Pierce',
  'Fort Pierce North',
  'Fort Walton Beach',
  'Fort White',
  'Fountain',
  'Four Corners',
  'Fowlers Bluff',
  'Frances Terrace',
  'Freeport',
  'Frostproof',
  'Fruitland Park',
  'Fullers Earth',
  'Fussels Corner',
  'Gainesville',
  'Gardner',
  'Gateway',
  'Georgetown',
  'Gibsonton',
  'Gifford',
  'Ginebra',
  'Glen Ridge',
  'Glen St. Mary',
  'Glencoe',
  'Golden Gate',
  'Golden Lakes',
  'Golf',
  'Gonzalez',
  'Goodland',
  'Goodwins Island',
  'Gordon',
  'Gotha',
  'Graceville',
  'Grand Island',
  'Grand Ridge',
  'Grandin',
  'Grant-Valkaria',
  'Grayton Beach',
  'Green Cove Springs',
  'Greenacres',
  'Greensboro',
  'Greenville',
  'Greenwood',
  'Gretna',
  'Grosh',
  'Grove City',
  'Groveland',
  'Gulf Breeze',
  'Gulf Hammock',
  'Gulf Stream',
  'Gulfport',
  'Haines City',
  'Haines Creek',
  'Hallandale Beach',
  'Hamburg',
  'Hampton',
  'Hampton Springs',
  'Hamptons at Boca Raton',
  'Harlem Heights',
  'Hastings',
  'Hawthorne',
  'Heathrow',
  'Hernando',
  'Hernando Beach',
  'Hesperides',
  'Hialeah',
  'Hidden Creek',
  'High Point',
  'High Springs',
  'Highland Beach',
  'Highland View',
  'Hillcrest Heights',
  'Hilliard',
  'Hillsboro Beach',
  'Historic Downtown Apalachicola',
  'Hobe Sound',
  'Holder',
  'Holiday',
  'Holly Hill',
  'Hollywood',
  'Holmes Beach',
  'Holopaw',
  'Holt',
  'Homeland',
  'Homestead',
  'Homosassa',
  'Homosassa Springs',
  'Horseshoe Beach',
  'Hosford',
  'Howey in the Hills',
  'Hudson',
  'Hunters Creek',
  'Hurlburt Field',
  'Hypoluxo',
  'Immokalee',
  'Indialantic',
  'Indian Creek',
  'Indian Harbour Beach',
  'Indian Lake Estates',
  'Indian Pass',
  'Indian River Estates',
  'Indian River Shores',
  'Indian Rocks Beach',
  'Indian Shores',
  'Indiantown',
  'Inglis',
  'Intercession City',
  'Interlachen',
  'Inverness',
  'Inverness Highlands South',
  'Inwood',
  'Iona',
  'Irvine',
  'Isla Fleming',
  'Isla de Marco',
  'Islamorada',
  'Island Grove',
  'Jacksonville',
  'Jacksonville Beach',
  'Jacob City',
  'Jan Phyl Village',
  'Jardines Hialeah',
  'Jasper',
  'Jay',
  'Jena',
  'Jennings',
  'Jensen Beach',
  'Jonesville',
  'June Park',
  'Juno Beach',
  'Juno Isles',
  'Juno Ridge',
  'Jupiter',
  'Jupiter Inlet Colony',
  'Kathleen',
  'Kenansville',
  'Key Biscayne',
  'Key Colony Beach',
  'Key Largo',
  'Key West',
  'Keystone Heights',
  'Kinard',
  'Kings Point',
  'Kingsland',
  'Kissimmee',
  'La Crosse',
  'La Habana',
  'LaBelle',
  'Lacoochee',
  'Lady Lake',
  'Lago Mary',
  'Laguna Beach',
  'Lake Alfred',
  'Lake Buena Vista',
  'Lake Butler',
  'Lake City',
  'Lake Como',
  'Lake Fern',
  'Lake Geneva',
  'Lake Hamilton',
  'Lake Harbor',
  'Lake Helen',
  'Lake Panasoffkee',
  'Lake Park',
  'Lake Placid',
  'Lake Wales',
  'Lake Worth',
  'Lake Worth Corridor',
  'Lakeland',
  'Lakeport',
  'Lakeshore',
  'Lakewood',
  'Lakewood Ranch',
  'Lamont',
  'Lanark Village',
  "Land O' Lakes",
  'Lantana',
  'Largo',
  'Lauderdale-by-the-Sea',
  'Lauderhill',
  'Laurel',
  'Laurel Hill',
  'Lawtey',
  'Layton',
  'Lecanto',
  'Lee',
  'Leesburg',
  'Lehigh Acres',
  'Leisure City',
  'Lely',
  'Lemon Bluff',
  'Lillian',
  'Lindgren Acres',
  'Lisbon',
  'Lithia',
  'Live Oak',
  'Lloyd',
  'Lochloosa',
  'Long Key',
  'Longboat Key',
  'Longwood',
  'Lorida',
  'Lowell',
  'Lower Grand Lagoon',
  'Loxahatchee',
  'Lulu',
  'Lutz',
  'Lynn Haven',
  'Macclenny',
  'Madeira Beach',
  'Madison',
  'Magnolia Bluffs',
  'Maitland',
  'Malabar',
  'Malone',
  'Manalapan',
  'Manattee Road',
  'Mango',
  'Marathon',
  'Margate',
  'Marianna',
  'Marineland',
  'Marion Oaks',
  'Martin',
  'Mary Esther',
  'Masaryktown',
  'Mascotte',
  'Matlacha',
  'Matlacha Isles-Matlacha Shores',
  'Mayo',
  'McDavid',
  'McGregor',
  'McIntosh',
  'Mcalpin',
  'Medart',
  'Melbourne',
  'Melbourne Beach',
  'Melbourne Village',
  'Melbourne occidental',
  'Melrose',
  'Memphis',
  'Meridian',
  'Merritt Island',
  'Mexico Beach',
  'Miami',
  'Miami Beach',
  'Miami Gardens',
  'Miami Lakes',
  'Miami Shores',
  'Miami Springs',
  'Micanopy',
  'Micco',
  'Miccosukee',
  'Middleburg',
  'Midway',
  'Milligan',
  'Milton',
  'Mims',
  'Minneola',
  'Miramar',
  'Miramar Beach',
  'Mission Bay',
  'Molino',
  'Monticello',
  'Montverde',
  'Moore Haven',
  'Morriston',
  'Mossy Head',
  'Mount Dora',
  'Mount Plymouth',
  'Mulat',
  'Mulberry',
  'Murdock',
  'Myakka City',
  'Myrtle Grove',
  'Nalcrest',
  'Naples',
  'Naples norte',
  'Nassauville',
  'Navarre',
  'Negrotown Knoll',
  'Neptune Beach',
  'New Hope',
  'New Port Richey',
  'New Smyrna Beach',
  'Newberry',
  'Newport',
  'Niceville',
  'No Name Key',
  'Nobleton',
  'Nocatee',
  'Nokomis',
  'Noma',
  'North Bay Village',
  'North Beach',
  'North Fort Myers',
  'North Lauderdale',
  'North Miami',
  'North Miami Beach',
  'North Palm Beach',
  'North Port',
  'North Redington Beach',
  'North River Shores',
  'North Weeki Wachee',
  'O Brien',
  'Oak Hill',
  'Oakland Park',
  'Ocala',
  'Ocean Breeze Park',
  'Ocean City',
  'Ocean Ridge',
  'Ochlockonee Bay',
  'Ochopee',
  'Ocklawaha',
  'Ocoee',
  'Odessa',
  'Ojus',
  'Okahumpka',
  'Okeechobee',
  'Old Myakka',
  'Old Town',
  'Oldsmar',
  'Olga',
  'Olustee',
  'Ona',
  'Oneco',
  'Opa-Locka',
  'Orange Beach',
  'Orange City',
  'Orange Heights',
  'Orange Lake',
  'Orange Park',
  'Orange Springs',
  'Orangetree',
  'Orchid',
  'Orient Park',
  'Oriole Beach',
  'Orlando',
  'Ormond Beach',
  'Ormond-by-the-Sea',
  'Oslo',
  'Osprey',
  'Osprey Village',
  'Osteen',
  'Otter Creek',
  'Overstreet',
  'Oviedo',
  'Oxford',
  'Ozello',
  'Pace',
  'Pahokee',
  'Painters Hill',
  'Paisley',
  'Palatka',
  'Palm Beach',
  'Palm Beach Gardens',
  'Palm City',
  'Palm Coast',
  'Palm Harbor',
  'Palm Shores',
  'Palm Springs',
  'Palm Springs North',
  'Palmdale',
  'Palmetto',
  'Panacea',
  'Panama City Beach',
  'Paradise Heights',
  'Parker',
  'Parkland',
  'Parque Highland',
  'Parrish',
  'Patrick Air Force Base',
  'Paxton',
  'Pembroke Pines',
  'Penney Farms',
  'Pensacola',
  'Pensacola Beach',
  'Perdido Key',
  'Perrine',
  'Perry',
  'Pierson',
  'Pine Forest',
  'Pine Island',
  'Pine Lakes',
  'Pine Manor',
  'Pine Ridge',
  'Pinecrest',
  'Pineland',
  'Pinellas Park',
  'Pinetta',
  'Pittman',
  'Pittsburg',
  'Placid Lakes',
  'Placida',
  'Plant City',
  'Plantation',
  'Plantation Island',
  'Playa Keaton',
  'Playas de Fort Pierce',
  'Poinciana',
  'Polk City',
  'Pomona Park',
  'Pompano Beach',
  'Ponce Inlet',
  'Ponce de León',
  'Ponte Vedra',
  'Ponte Vedra Beach',
  'Porpoise Point',
  'Port Charlotte - Charlotte Harbor',
  'Port LaBelle',
  'Port Leon',
  'Port Mayaca',
  'Port Orange',
  'Port Richey',
  'Port Saint John',
  'Port Salerno',
  'Port St. Joe',
  'Pretty Bayou',
  'Princeton',
  'Puerto de Santa Lucía',
  'Punta Gorda',
  'Punta Rassa',
  'Quincy',
  'Raiford',
  'Reavills Corner',
  'Reddick',
  'Redington Beach',
  'Redington Shores',
  'Ridge Manor',
  'Rio',
  'River Park',
  'River Ranch',
  'Riverview',
  'Riviera Beach',
  'Rochelle',
  'Rock Harbor',
  'Rock Hill',
  'Rockledge',
  'Roseland',
  'Rosewood',
  'Rotonda West',
  'Royal Palm Beach',
  'Ruskin',
  'Safety Harbor',
  'Saint Cloud',
  'Saint George',
  'Saint Leo',
  'Saint Teresa',
  'Salt Springs',
  'Samoset',
  'Samson',
  'Samsula-Spruce Creek',
  'San Antonio',
  'San Carlos Park',
  'San Mateo',
  'San Petersburgo',
  'San Petersburgo-Clearwater',
  'Sandalfoot Cove',
  'Sanderson',
  'Sandestin',
  'Sanford',
  'Sanibel',
  'Santa Fe',
  'Santa Rosa Beach',
  'Sarasota',
  'Satellite Beach',
  'Satsuma',
  'Scotland',
  'Scottsmoor',
  'Sea Ranch Lakes',
  'Seacrest',
  'Seagrass',
  'Sebastian',
  'Sebring',
  'Sebring Shores',
  'Seffner',
  'Seminole',
  'Servicio de Taxi Sorrento',
  'Sevilla',
  'Sewall s Point',
  'Shady Grove',
  'Shalimar',
  'Sharpes',
  'Shired Island',
  'Siesta Key',
  'Silver Lake',
  'Silver Springs',
  'Silver Springs Shores',
  'Singer Island',
  'Slocomb',
  'Sneads',
  'Solana',
  'Sopchoppy',
  'South Apopka',
  'South Bay',
  'South Palm Beach',
  'South Patrick Shores',
  'Southport',
  'Southwest Ranches',
  'Sparr',
  'Spring Hill',
  'Spring Lake',
  'St. Augustine',
  'St. Augustine Beach',
  'St. Cloud',
  'St. George',
  'St. James City',
  'St. Johns',
  'St. Lucie Village',
  'St. Marks',
  'St. Marys',
  'St. Pete Beach',
  'Stanton',
  'Starke',
  'Steinhatchee',
  'Stuart',
  'Sugarmill Woods',
  'Sumatra',
  'Summer Haven',
  'Summerfield',
  'Summerland Key',
  'Sumner',
  'Sumterville',
  'Sun City Center',
  'Suncoast Estates',
  'Sunny Hills',
  'Sunny Isles Beach',
  'Sunnyside',
  'Sunrise',
  'Sunset Corners',
  'Suntree',
  'Surfside',
  'Survey Creek',
  'Suwannee',
  'Svea',
  'Sydney',
  'Sylvan Shores',
  'Tallahassee',
  'Tallevast',
  'Tamarac',
  'Tampa',
  'Tangerine',
  'Tarpon Springs',
  'Tarrytown',
  'Tavares',
  'Tavernier',
  'Taylor Creek',
  'Tequesta',
  'Terra Ceia',
  'The Villages',
  'Thonotosassa',
  'Three Oaks',
  'Tice',
  'Tierra Verde',
  'Tiger Point',
  'Timber Pines',
  'Titusville',
  'Treasure Island',
  'Trenton',
  'Trilby',
  'Trilcoochee',
  'Tropical Gulf Acres',
  'Truckland',
  'Turkey Creek',
  'Two Egg',
  'Umatilla',
  'University Circle',
  'Upper Grand Lagoon',
  'Valparaiso',
  'Valrico',
  'Valrico',
  'Venecia',
  'Venus',
  'Vermont Heights',
  'Verna',
  'Vernon',
  'Vero Beach',
  'Vero Beach South',
  'Vero Lake Estates',
  'Vicksburg',
  'Village of Golf',
  'Villas',
  'Vineyards',
  'Wabasso',
  'Wabasso Beach',
  'Wacissa',
  'Wakulla Beach',
  'Wakulla Springs',
  'Waldo',
  'Walnut Hill',
  'Warrington',
  'Watersound',
  'Watertown',
  'Wauchula',
  'Wauchula Hills',
  'Waukeenah',
  'Wausau',
  'Waverly',
  'Webster',
  'Wedgefield',
  'Weeki Wachee Gardens',
  'Weirsdale',
  'Wekiwa Springs',
  'Welaka',
  'Wellborn',
  'Wellington',
  'Wesley Chapel',
  'West Bay',
  'West Bradenton',
  'West De Land',
  'West Dixie Bend',
  'West Lake',
  'West Miami',
  'West Palm Beach',
  'West Panama City Beach',
  'West Pensacola',
  'West Vero Corridor',
  'Westgate',
  'Weston',
  'Westville',
  'Wewahitchka',
  'Whisper Walk',
  'Whispering Pines',
  'White City',
  'White Springs',
  'Whites Ford',
  'Wilbur-By-The-Sea',
  'Wildwood',
  'Williston',
  'Williston Highlands',
  'Willow',
  'Wilton Manors',
  'Wimauma',
  'Windermere',
  'Windsor',
  'Winter Beach',
  'Winter Garden',
  'Winter Haven',
  'Winter Park',
  'Winter Springs',
  'Woodlawn Beach',
  'Woodrings',
  'Woodville',
  'Worthington Springs',
  'Wright',
  'Wulfert',
  'Wynnehaven Beach',
  'Yalaha',
  'Yankeetown',
  'Yeehaw Junction',
  'Youngstown',
  'Yulee',
  'Zellwood',
  'Zephyrhills',
  'Zolfo Springs',
  'Zuber',
]

export const campaings = {
  fl: {
    CybertruckFL: 'CybertruckFL',
    LearnAndWinRoofing: 'LearnAndWinRoofing',
    HomeWebsiteFormFL: 'HomeWebsiteFormFL',
    roofing_fl: 'roofing_fl',
    switchSolarEnergy: 'switchSolarEnergy',
    LpSolar_fl: 'LpSolar_fl',
    LpRoofing_fl: 'LpRoofing_fl',
  },
  pr: {
    Firma_y_pisalo_cyber_x2: 'Firma_y_pisalo_cyber_x2',
    CyberTruckGiveaway: 'CyberTruckGiveaway',
    Anker_pr: 'anker_pr',
    BSN: 'BSN',
    switch_energia_solar: 'switch_energia_solar',
    CMBA: 'CMBA',
    cambiate_a_energia_de_la_buena: 'cambiate_a_energia_de_la_buena',
    tesla_50k: 'tesla_50k',
    confia_en_los_expertos_carmen: 'confia_en_los_expertos_carmen',
    roofing_pr: 'roofing_pr',
    HomeWebsiteFormPR: 'HomeWebsiteFormPR',
    Huracanes: 'Huracanes',
    HuracanesB: 'HuracanesB',
    ReferidosNew: 'ReferidosNew',
    RainCoat: 'RainCoat',
    FuerzasDeVentas: 'FuerzasDeVentas',
    TecnicoInstalacion: 'TecnicoInstalacion',
    TecnicoRoofing: 'TecnicoRoofing',
    RayitosDeSolWH: 'rayitos-de-sol-wh',
    AdultoMayor: 'adulto-mayor-wh',
    Firma_y_pisalo_cyber: 'firma_y_pisalo_cyber',
  },
}

export const translationsForm_DN = {
  en: {
    firstName: 'First Name',
    lastName: 'Last Name',
    phone: 'Phone',
    email: 'Email',
    city: 'City',
    sales_Rep_Phone: 'Sales Rep Phone',
    destination: 'Destination',
    ownHome: 'Do you own your home?',
    propertyType: 'Describe your property type?',
    roofType: 'Do you have a clay tile roof?',
    roofType2: "*Please note that if your home's roof has clay tiles you do not qualify for the prize.",
    roofAge: 'Roof Age',
    monthlyBill: 'AVG. Monthly Electricity Bill',
    consultationType: 'Roof hurricane safety consultation type',
    youavaliable: 'Are you available for a virtual or in-person meeting?',
    single: 'Single Family Home',
    apartment: 'Apartment',
    shingle: 'Shingle',
    flat: 'Flat',
    concreteTile: 'Concrete Tile',
    metal: 'Metal',
    clayTile: 'Clay Tile',
    other: 'Other',
    virtual: 'Virtual',
    inperson: 'In Person',
    yes: 'YES',
    next: 'NEXT',
    previous: 'BACK',
    send: 'SEND',
    year: 'years',
    lessMore: 'Less than',
  },
  es: {
    firstName: 'Nombre',
    lastName: 'Apellido',
    phone: 'Teléfono',
    email: 'Email',
    city: 'Ciudad',
    sales_Rep_Phone: 'Teléfono de vendedor',
    destination: 'Destino',
    ownHome: '¿Es dueño de su casa?',
    propertyType: 'Describa el tipo de propiedad',
    roofType: '¿Tienes un techo con tejas de arcilla? ',
    roofType2: '*Ten en cuenta que si el techo de tu hogar tiene tejas de arcilla no califica para el premio.',
    roofAge: 'Edad del techo',
    monthlyBill: 'Factura de electricidad mensual promedio',
    consultationType: 'Tipo de consulta de seguridad contra huracanes en el techo',
    youavaliable: '¿Está disponible para una reunión virtual o en persona?',
    single: 'Casa de una sola familia',
    shingle: 'Teja',
    flat: 'Plano',
    concreteTile: 'baldosa de concreto',
    metal: 'Metal',
    clayTile: 'Baldosa de arcilla ',
    other: 'Otro',
    virtual: 'Virtual',
    inperson: 'En persona',
    apartment: 'Apartamento',
    yes: 'Sí',
    next: 'SIGUIENTE',
    previous: 'ANTERIOR',
    send: 'ENVIAR',
    year: 'años',
    lessMore: 'Menos de',
    errorName: 'Nombre requerido',
  },
}
export const translationsForm = {
  en: {
    firstName: 'First Name',
    lastName: 'Last Name',
    phone: 'Phone',
    email: 'Email',
    Phone: 'Phone',
    sales_Rep_Phone: 'Sales Rep Phone',
    city: 'City',
    destination: 'Destination',
    Presenter_Appointment: 'Date',
    Appointment_Type: 'Appointment Type',
    products: 'Products',
    seletedProducts: 'Selected Products',
    send: 'SEND',
    reqName: 'Name required',
    reqLastname: 'Last Name required',
    reqEmail: 'Email required',
    reqPhone: 'Phone required',
    reqPresenter_Appointment: 'Presenter Appointment required',
    reqAppointment_Type: 'Appointment Type required',

    errorName: 'Enter only letters and/or spaces.',
    errorLastname: 'Enter only letters and/or spaces.',
    errorEmail: 'Enter a valid email address.',
    errorPhone: 'Enter only numbers, cannot start with 1 or 0, must be 10 digits',
    reqSales_Rep_Phone: 'Sales Rep Phone required',
    errorSales_Rep_Phone: 'Enter only numbers, cannot start with 1 or 0, must be 10 digits',
    errorPresenter_Appointment: 'Enter a valid date, format: MM/DD/YYYY',
    errorAppointment_Type: 'Select an appointment type',
  },
  es: {
    firstName: 'Nombre(s)',
    lastName: 'Apellido(s)',
    phone: 'Teléfono',
    email: 'Correo Electrónico',
    city: 'Ciudad',
    Phone: 'Teléfono',
    sales_Rep_Phone: 'Teléfono de Vendedor',
    Presenter_Appointment: 'Fecha',
    Appointment_Type: 'Tipo de Cita',
    products: 'Productos',
    seletedProducts: 'Productos Seleccionados',
    destination: 'Destino',
    send: 'ENVIAR',
    reqName: 'Nombre requerido',
    reqLastname: 'Apellido requerido',
    reqPhone: 'Teléfono requerido',
    reqEmail: 'Email requerido',
    reqPresenter_Appointment: 'Cita de presentador requerida',
    reqAppointment_Type: 'Tipo de cita requerida',

    errorName: 'Ingrese solo letras y/o espacios.',
    errorLastname: 'Ingrese solo letras y/o espacios.',
    errorEmail: 'Ingrese una dirección de correo electrónico válida.',
    errorPhone: 'Ingrese solo números, no puede comenzar con 1 o 0, debe tener 10 dígitos',
    reqSales_Rep_Phone: 'Teléfono de vendedor requerido',
    errorSales_Rep_Phone: 'Ingrese solo números, no puede comenzar con 1 o 0, debe tener 10 dígitos',
    errorPresenter_Appointment: 'Ingrese una fecha válida, formato: MM/DD/YYYY',
    errorAppointment_Type: 'Seleccione un tipo de cita',
  },
}

export const imagenesNavBar = {
  Logo: 'https://windmar-website-cms.s3.amazonaws.com/NavBar/LogoWindmar.svg',
  BanderaPR: 'https://windmar-website-cms.s3.amazonaws.com/NavBar/BanderaPuertoRico.svg',
  BanderaFL: 'https://windmar-website-cms.s3.amazonaws.com/NavBar/BanderaEEUU.svg',
  FondoFL: 'https://windmar-website-cms.s3.amazonaws.com/NavBar/FondoBanderaEEUU.svg',
  FondoPR: 'https://windmar-website-cms.s3.amazonaws.com/NavBar/FondoBanderaPR.svg',
  FaceMobile: 'https://windmar-website-cms.s3.amazonaws.com/NavBar/FacebookMobile.svg',
  InstaMobile: 'https://windmar-website-cms.s3.amazonaws.com/NavBar/InstagramMobile.svg',
  YouMobile: 'https://windmar-website-cms.s3.amazonaws.com/NavBar/YouTubeMobile.svg',
  LinkMobile: 'https://windmar-website-cms.s3.amazonaws.com/NavBar/LinkedinMobile.svg',
  SistemaSolar: 'https://windmar-website-cms.s3.amazonaws.com/NavBar/SistemaSolar.svg',
  PowerWall: 'https://windmar-website-cms.s3.amazonaws.com/NavBar/PowerWall.svg',
  Roofing: 'https://windmar-website-cms.s3.amazonaws.com/NavBar/Roofing.svg',
  Anker: 'https://windmar-website-cms.s3.amazonaws.com/NavBar/Anker.svg',
}

export const ArteQueIluminaData = {
  arte2024: [
    {
      slug: 'san-juan-mark',
      title: 'Mark “Kidnetick” Rivera',
      town: 'SAN JUAN',
      banner: 'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/SAN+JUAN-MARK/SANJUAN-MARK-1.webp',
      content: {
        artist: 'Mark Rivera, conocido artísticamente como',
        lastName: 'Kidnetick',
        bioArtist:
          'Es un artista multidisciplinario que se especializa en esculturas que toman vida con efectos lumínicos. Sus piezas se han exhibido internacionalmente y hasta en festivales como Burning Man, con su pieza “El Jibaro”.',
        description:
          'Su mural es una respuesta creativa al efecto que los apagones tienen en nuestros enseres mientras hace una oda a las casas humildes de los jíbaros puertorriqueños en las piezas de Rafael Tufiño. En la noche todos los enseres se encienden con el poder de una batería instalada por el equipo de WindMar Home. De día se puede apreciar cada pieza de la escultura y de noche es un espectáculo que no te puedes perder.',
        video: 'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/SAN+JUAN-MARK/VIDEO-SANJ+UAN+MARK.mp4',
        text: '',
        slide: [
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/SAN+JUAN-MARK/SANJUAN-MARK-1.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/SAN+JUAN-MARK/SANJUAN-MARK-2.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/SAN+JUAN-MARK/SANJUAN-MARK-3.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/SAN+JUAN-MARK/SANJUAN-MARK-4.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/SAN+JUAN-MARK/SANJUAN-MARK-5.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/SAN+JUAN-MARK/SANJUAN-MARK-6.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/SAN+JUAN-MARK/SANJUAN-MARK-7.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/SAN+JUAN-MARK/SANJUAN-MARK-8.webp',
        ],
        map: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3784.7528259967435!2d-66.0807856!3d18.4495285!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8c036f80c44df633%3A0xd3a65353bc2f8ffb!2sGraziani%20Restaurante!5e0!3m2!1ses!2sco!4v1734526474379!5m2!1ses!2sco',
      },
    },
    {
      slug: 'caguas-bianca',
      title: 'The Unusual Girls',
      town: 'Caguas',
      banner: 'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CAGUAS-BIANCA/CAGUAS-BIANCA-2.webp',
      content: {
        artist: 'Bianca Montoya',
        bioArtist:
          'Puertorriqueña con más de 10 años en la industria creativa, es la creadora de Unusual Girls, un proyecto que celebra la autenticidad y diversidad a través de retratos vibrantes y glamorosos. Su enfoque en la expresión única y la conexión con el entorno resuena con la visión de un futuro renovable, destacando cómo el arte puede inspirar transformación y sostenibilidad.',
        description:
          '“El Portal” es una representación de la naturaleza y la oscuridad y su relación con el sol. SIn el sol, no hay luna, no hay vegetación, no hay vida. La pieza le da homenaje a este increible recurso y muestra como ambas diosas estan atraidas al portal de luz para sobrevivir en un futuro 100% renovable.',
        video: 'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CAGUAS-BIANCA/CAGUAS-BIANCA-VIDEO.mp4',
        text: '',
        slide: [
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CAGUAS-BIANCA/CAGUAS-BIANCA-1.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CAGUAS-BIANCA/CAGUAS-BIANCA-2.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CAGUAS-BIANCA/CAGUAS-BIANCA-3.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CAGUAS-BIANCA/CAGUAS-BIANCA-4.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CAGUAS-BIANCA/CAGUAS-BIANCA-5.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CAGUAS-BIANCA/CAGUAS-BIANCA-6.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CAGUAS-BIANCA/CAGUAS-BIANCA-7.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CAGUAS-BIANCA/CAGUAS-BIANCA-8.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CAGUAS-BIANCA/CAGUAS-BIANCA-9.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CAGUAS-BIANCA/CAGUAS-BIANCA-10.webp',
        ],
        map: 'https://www.google.com/maps/embed?pb=!1m17!1m12!1m3!1d3789.571601428295!2d-66.038421!3d18.229599999999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m2!1m1!2zMTjCsDEzJzQ2LjYiTiA2NsKwMDInMTguMyJX!5e0!3m2!1ses-419!2sco!4v1734526443180!5m2!1ses-419!2sco',
      },
    },
    {
      slug: 'orocovis-Vero',
      title: 'Vero Rivera',
      town: 'Orocovis',
      banner: 'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/OROCOVIS-VERO/OROCOVIS-VERO-13.webp',
      content: {
        artist: 'Vero Rivera',
        bioArtist:
          'Nacida en San Juan, Puerto Rico, explora en su arte las contradicciones entre la fugacidad de la vida y el deseo humano de permanencia. A través de elementos naturales y sus cualidades ornamentales, representa cómo las relaciones humanas imitan la capacidad de la naturaleza para adaptarse, sanar y prosperar según su entorno y experiencias.',
        description:
          '“Entre montañas y luz”, realizada con la técnica de cianotipo, rinde homenaje a la energía solar y a la conexión entre la naturaleza y la sostenibilidad. Incorporando hojas de café de Café Cibeles en Orocovis, la pieza destaca la importancia de la luz solar como fuente de vida y resalta valores como el cooperativismo y la autogestión en Puerto Rico.',
        video: 'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/OROCOVIS-VERO/VIDEO-OROVOCIS+-VERO.mp4',
        text: 'Estas hojas, inmortalizadas en el característico azul profundo del cianotipo, se convierten en protagonistas de una composición que invita a reflexionar sobre la interdependencia entre lo natural y lo humano. La obra no solo exalta la energía renovable, sino también la esencia de nuestra tierra y su capacidad para sostener y transformar vidas.',
        slide: [
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/OROCOVIS-VERO/OROCOVIS-VERO-1.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/OROCOVIS-VERO/OROCOVIS-VERO-2.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/OROCOVIS-VERO/OROCOVIS-VERO-3.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/OROCOVIS-VERO/OROCOVIS-VERO-4.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/OROCOVIS-VERO/OROCOVIS-VERO-5.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/OROCOVIS-VERO/OROCOVIS-VERO-6.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/OROCOVIS-VERO/OROCOVIS-VERO-7.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/OROCOVIS-VERO/OROCOVIS-VERO-8.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/OROCOVIS-VERO/OROCOVIS-VERO-9.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/OROCOVIS-VERO/OROCOVIS-VERO-10.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/OROCOVIS-VERO/OROCOVIS-VERO-11.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/OROCOVIS-VERO/OROCOVIS-VERO-12.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/OROCOVIS-VERO/OROCOVIS-VERO-13.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/OROCOVIS-VERO/OROCOVIS-VERO-14.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/OROCOVIS-VERO/OROCOVIS-VERO-15.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/OROCOVIS-VERO/OROCOVIS-VERO-16.webp',
        ],
        map: 'https://www.google.com/maps/embed?pb=!1m17!1m12!1m3!1d3789.600224292261!2d-66.391573!3d18.228286!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m2!1m1!2zMTjCsDEzJzQxLjgiTiA2NsKwMjMnMjkuNyJX!5e0!3m2!1ses!2sco!4v1734526367533!5m2!1ses!2sco',
      },
    },
    {
      slug: 'cataño-nano',
      title: 'Nano López',
      town: 'Cataño',
      banner: 'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CATANO-NANDO/CATANO-NANDO-9.webp',
      content: {
        artist: 'Nano López',
        bioArtist:
          'Fernando "Nano" López-Cepero Ortiz, artista multidisciplinario puertorriqueño, se especializa en escultura, pintura a gran escala y arte digital que conecta la naturaleza con el comportamiento humano a través de la tecnología. Con un bachillerato en artes plásticas y experiencia en la industria del cine, ha colaborado en proyectos internacionales con artistas como Abey Charrón y participado en eventos como La Biennale di Venezia, Los Muros Hablan y Burning Man, destacándose por su innovación y versatilidad.',
        description:
          '"Otra Cepa," es un llamado a la esperanza y al cambio, recordándonos el privilegio de vivir en un entorno rico en biodiversidad y energía renovable. Representa la transición necesaria de los combustibles fósiles, simbolizados por peluches de dinosaurios, hacia un futuro iluminado por los recursos naturales que nos rodean, encarnados por los cucubanos, una especie afectada por la contaminación y la pérdida de su hábitat',
        video: 'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CATANO-NANDO/VIDEO-NANDO_CATANO.mp4',
        text: 'La pieza nos exhorta a reflexionar sobre nuestro impacto en el planeta y a proteger nuestro patrimonio natural, asegurando que generaciones futuras puedan disfrutar de su abundancia. Con el pitirre como símbolo de lucha y perseverancia, la obra invita a convertirnos en agentes de cambio, levantando la mirada hacia un país más digno, sustentable y renovable.',
        slide: [
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CATANO-NANDO/CATANO-NANDO-1.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CATANO-NANDO/CATANO-NANDO-2.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CATANO-NANDO/CATANO-NANDO-3.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CATANO-NANDO/CATANO-NANDO-4.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CATANO-NANDO/CATANO-NANDO-5.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CATANO-NANDO/CATANO-NANDO-6.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CATANO-NANDO/CATANO-NANDO-7.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CATANO-NANDO/CATANO-NANDO-8.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CATANO-NANDO/CATANO-NANDO-9.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CATANO-NANDO/CATANO-NANDO-10.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CATANO-NANDO/CATANO-NANDO-11.webp',
        ],
        map: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3784.9428387355333!2d-66.1199753!3d18.4409043!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8c0369485aca7bf5%3A0xe64808f9b9f025ee!2s158%20Avenida%20Barbosa%2C%20Cata%C3%B1o%2C%2000962%2C%20Puerto%20Rico!5e0!3m2!1ses!2sco!4v1734526422963!5m2!1ses!2sco',
      },
    },
    {
      slug: 'cabo-rojo-abey',
      title: 'Abey Charrón',
      town: 'Cabo Rojo',
      banner: 'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CABO-ROJO/cabo-rojo-Abey-6.webp',
      content: {
        artist: 'Abey Charrón',
        bioArtist:
          'Abey R. Charrón Walker, fotógrafo puertorriqueño nacido en Río Piedras, combina elementos tradicionales y no convencionales para destacar íconos culturales de la vida caribeña. Su obra ha alcanzado reconocimiento internacional, siendo presentada en más de 40 exposiciones, entre ellas muestras en París, Berlín y la prestigiosa Bienal de Fotografía de Puerto Rico. Con técnicas únicas como la impresión en techos de zinc, aborda temas sociales como el crimen y la decadencia caribeña, dejando una marca distintiva en el mundo del arte.',
        description:
          '"The West is the Best," ecelebra la belleza del sol y los atardeceres en el oeste de Puerto Rico, rindiendo homenaje a uno de nuestros recursos más abundantes y renovables. Representa un momento de unión y conexión humana al disfrutar el mágico instante que el sol de oculta, con un velero en el horizonte simbolizando libertad e independencia energética. Es un tributo a la naturaleza y a la esperanza que renace con cada nuevo día.',
        video: 'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CABO-ROJO/VIDEO-CABO+ROJO-ABEY.mp4',
        text: 'La pieza nos exhorta a reflexionar sobre nuestro impacto en el planeta y a proteger nuestro patrimonio natural, asegurando que generaciones futuras puedan disfrutar de su abundancia. Con el pitirre como símbolo de lucha y perseverancia, la obra invita a convertirnos en agentes de cambio, levantando la mirada hacia un país más digno, sustentable y renovable.',
        slide: [
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CABO-ROJO/cabo-rojo-Abey-1.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CABO-ROJO/cabo-rojo-Abey-2.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CABO-ROJO/cabo-rojo-Abey-3.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CABO-ROJO/cabo-rojo-Abey-4.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CABO-ROJO/cabo-rojo-Abey-5.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CABO-ROJO/cabo-rojo-Abey-6.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CABO-ROJO/cabo-rojo-Abey-7.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CABO-ROJO/cabo-rojo-Abey-8.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CABO-ROJO/cabo-rojo-Abey-9.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CABO-ROJO/cabo-rojo-Abey-10.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CABO-ROJO/cabo-rojo-Abey-11.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CABO-ROJO/cabo-rojo-Abey-12.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CABO-ROJO/cabo-rojo-Abey-13.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CABO-ROJO/cabo-rojo-Abey-14.webp',
          'https://windmar-website-cms.s3.us-east-1.amazonaws.com/LPs/ArteQueIlumina/CABO-ROJO/cabo-rojo-Abey-15.webp',
        ],
        map: 'https://www.google.com/maps/embed?pb=!1m17!1m12!1m3!1d3794.004797038592!2d-67.1738!3d18.024981!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m2!1m1!2zMTjCsDAxJzI5LjkiTiA2N8KwMTAnMjUuNyJX!5e0!3m2!1ses!2sco!4v1734526300088!5m2!1ses!2sco',
      },
    },
  ],
  arte2023: [
    {
      slug: 'rafael_algarin',
      title: 'Rafael Algarín',
      town: 'ISABELA',
      banner: 'https://windmar-website-cms.s3.amazonaws.com/Windmar1.0/LANDING+PAGE/energia-y-arte-en-isabella-puerto-rico.webp',
    },
    {
      slug: 'david-don-rimx',
      title: 'David “Don Rimx”',
      town: 'FAJARDO',
      banner: 'https://windmar-website-cms.s3.amazonaws.com/Windmar1.0/LANDING+PAGE/energia-y-arte-en-fajardo-puerto-rico.webp',
    },
    {
      slug: 'alejandro-rodriguez',
      title: 'Alejandro Rodríguez',
      town: 'PONCE',
      banner: 'https://windmar-website-cms.s3.amazonaws.com/Windmar1.0/LANDING+PAGE/energia-y-arte-en-ponce-puerto-rico.webp',
    },
    {
      slug: 'gabriela-y-patricia-urrutia',
      title: 'Gabriela y Patricia Urrutia',
      town: 'AGUADILLA',
      banner: 'https://windmar-website-cms.s3.amazonaws.com/Windmar1.0/LANDING+PAGE/energia-y-arte-en-aguadilla-puerto-rico.webp',
    },
    {
      slug: 'juan-del-pueblo',
      title: 'Juan del Pueblo',
      town: 'HATILLO',
      banner: 'https://windmar-website-cms.s3.amazonaws.com/Windmar1.0/LANDING+PAGE/energia-y-arte-en-hatillo-puerto-rico.webp',
    },
    {
      slug: 'celso-gonzales',
      title: 'Celso Gonzales',
      town: 'LOÍZA',
      banner: 'https://windmar-website-cms.s3.amazonaws.com/LPs/ArteQueIlumina/S3_05330+2.webp',
    },
  ],
}
